version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: jsforce-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: jsforce-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: npm test
